[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

# arbitrary operations on chips and mult
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "update_hand_text({delay = 0}, {chips = extras.hand_chips and hand_chips, mult = extras.mult and mult})"
position = "before"
payload = '''
if effects.jokers.Eqmult_mod then mult = Eqmult_mod;extras.mult = true end
'''
match_indent = true