[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "card"
pattern = "sell_cost = sell_cost + G.jokers.cards[i].sell_cost"
position = "at"
payload = '''
sell_cost = (sell_cost or 0) + (G.jokers.cards[i].sell_cost or 0)
'''
match_indent = true
