[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "{n=G.UIT.O, config={object = DynaText({string = {' '..localize('ph_mr_bones')..' '}, colours = {G.C.FILTER}, shadow = true, pop_in = 0, scale = 0.5*scale, silent = true})}}"
position = "at"
payload = '''
{n=G.UIT.O, config={object = DynaText({string = {' '..(G.GAME.Ruby and localize(pseudorandom_element(Entropy.RubySaves, pseudoseed("hope"))) or localize('ph_mr_bones'))..' '}, colours = {G.C.FILTER}, shadow = true, pop_in = 0, scale = 0.5*scale*(1), silent = true, maxw = 5})}}
'''
match_indent = true