

[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.set == 'Booster' or self.ability.set == 'Spectral' then"
position = "at"
payload = '''
if self.ability.set == 'Booster' or self.ability.set == 'Spectral' or self.config.center.set == "RSpectral" then
'''
match_indent = true