[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
{n=G.UIT.O, config={id = 'hand_name', func = 'hand_text_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "handname_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.4})}},
'''
position = "before"
payload = '''
{n=G.UIT.O, config={id = 'cry_asc', func = 'entr_trans_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "entr_trans_num_text"}}, colours = {HEX("84e1ff")}, shadow = true, float = true, scale = scale*1})}},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
                chip_total_text = '',
'''
position = "after"
payload = '''
                entr_trans_num_text = '',
'''
match_indent = true